### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by davidsteinsland** [morrislaptop/AirbrakeCake#7]
`composer` installs the plugin as `Plugin/CakephpAirbrake`. This means CakePHP fails to load the plugin, as this is required instead:

```php
CakePlugin::load('AirbrakeCake', array(
    'path' => APP . 'Plugin/CakephpAirbrake/'
));
```

The trailing slash is very important here.

**Comment by morrislaptop** [comment]
Can you submit a pull request?

**Comment by davidsteinsland** [comment]
That depends — do you want to revert the composer name, fix the README, or add a "installer-name" to `composer.json`:

```json
"extra": {
    "installer-name": "AirbrakeCake"
}
```

**Comment by josegonzalez** [comment]
Setting the installer-name is preferred in this situation.

**Comment by davidsteinsland** [comment]
I second that.

**Comment by morrislaptop** [comment]
Agreed.
